spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: microservicecloud-config-atguigu-dev,version4
    
config: 
  info: microservicecloud-config-atguigu-dev,version4
  
---
spring:
  profiles: test   #测试环境
  application: 
    name: microservicecloud-config-atguigu-test,version4
 
 
